set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

bind J command-prompt -p "join pane from:" "join-pane -s '%%'"
bind S command-prompt -p "send pane to:" "join-pane -t '%%'"
bind s command-prompt -p "send pane to:" "join-pane -t '%%'"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g history-limit 50000

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

set-window-option -g mode-keys vi

set -g mouse on

set -ga terminal-overrides ',xterm*:smcup@:rmcup@'

set -as terminal-features ",*:hyperlinks"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-logging'

# Theme
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_host 'on' # Enables hostname in the status bar
set -g @rose_pine_hostname_short 'on' # Makes the hostname shorter by using tmux's '#h' format
set -g @rose_pine_date_time '' # It accepts the date UNIX command format (man date for info)
set -g @rose_pine_user 'on' # Turn on the username component in the statusbar
set -g @rose_pine_directory 'on' # Turn on the current folder component in the status bar

run '~/.tmux/plugins/tpm/tpm'
